source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.2.0'
gem 'puma', '~> 3.11'
# gem 'rack-timeout', '~> 0.4'
gem 'jbuilder', '~> 2.5'
gem 'pg', '~> 1.0'
gem 'redis-rails', '~> 5.0'
gem 'sidekiq', '~> 5.1'
# gem 'clockwork', '~> 2.0'
# gem 'kaminari', '~> 1.0'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'bootstrap', '~> 4.1.1'
gem 'font-awesome-rails', '~> 4.7'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails', '~> 4.3'
# gem 'bootsnap', '>= 1.1.0', require: false

# gem 'passwordless'
# gem 'dragonfly', '~> 1.1.3'
# gem 'activeadmin'
# gem 'devise'
# gem 'cancan'

group :development, :test do
  gem 'byebug', platform: :mri
end

group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

group :development do
  gem 'rack-mini-profiler', '~> 1.0'
  gem 'web-console', '~> 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data'
